### ISSUE TITLE
Outdated cmo_resources.json

### ISSUE THREAD

**Issue by hisplan** [mskcc/cmo#15]
There are some discrepancies between the `cmo_resources.json` file in the git repo vs. the one being used in the cluster. 

- Git Repo: `https://github.com/mskcc/cmo/blob/master/cmo/data/cmo_resources.json`
- Cluster: `/opt/common/CentOS_6-dev/cmo/cmo_resources.json`

For instance, the one in the git repo does not have trim galore, missing versions of some tools, and etc.

For instance, running `cmo_trimgalore` on a fresh Linux box fails with the key-not-found error message.

```
Traceback (most recent call last):
  File "/usr/local/bin/cmo_trimgalore", line 4, in <module>
    __import__('pkg_resources').run_script('cmo===4515eb7', 'cmo_trimgalore')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/cmo-4515eb7-py2.7.egg/EGG-INFO/scripts/cmo_trimgalore", line 35, in <module>
    verparser.add_argument("--version", choices=cmo.util.programs['trimgalore'].keys(), default="default")
KeyError: 'trimgalore'
```

**Comment by lordzappo** [comment]
There is a repo around the acutal file location, this location isn't maintained...one sec.
