### ISSUE TITLE
StopIteration

### ISSUE THREAD

**Issue by marcrobertdemassy** [mskcc/cmo#6]
Hi !

I am trying to run facets with these command lines (which has already been successfully used one very similar samples) : 

```
export PATH=$PATH:/opt/common/CentOS_6-dev/python/python-2.7.10/bin/
cmoflow_facets \
    --tumor-bam pathToBam \
    --normal-bam pathToBam \
    --workflow-mode LSF \
    --output-dir `pwd` \
    --purity_cval 300 \
    --cval 100 \
    —force
```

and I am getting this error : 

```
Found one sample key for this bam: W0000436F
Found one sample key for this bam: W0000438F
Traceback (most recent call last):
  File "/opt/common/CentOS_6-dev/python/python-2.7.10/bin/cmoflow_facets", line 4, in <module>
    __import__('pkg_resources').run_script('cmo===e766ccf-dirty', 'cmoflow_facets')
  File "/opt/common/CentOS_6-dev/python/python-2.7.10/lib/python2.7/site-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/opt/common/CentOS_6-dev/python/python-2.7.10/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1483, in run_script
    exec(code, namespace, namespace)
  File "/opt/common/CentOS_6-dev/python/python-2.7.10/lib/python2.7/site-packages/cmo-e766ccf_dirty-py2.7.egg/EGG-INFO/scripts/cmoflow_facets", line 126, in <module>
    (jobs, dependencies, name, terminal_job, count_jobs) = construct_workflow(args.tumor_bam, args.normal_bam, args.tag, facets_args, args.output_dir, snps=args.vcf, tumor_sample = args.tumor_name, normal_sample=args.normal_name, force=args.force)
  File "/opt/common/CentOS_6-dev/python/python-2.7.10/lib/python2.7/site-packages/cmo-e766ccf_dirty-py2.7.egg/EGG-INFO/scripts/cmoflow_facets", line 77, in construct_workflow
    value = next(it)
StopIteration
```

Not sure what's happening...

Thank very much for your help !

Marc

**Comment by lordzappo** [comment]
Hi Marc, are you still having this problem?   Sorry for the delay in reply, I was out of town.

**Comment by ckandoth** [comment]
Closing issue since we didn't hear back from OP.
